name: Download, Convert and Upload

on:
  workflow_dispatch: # manual trigger

jobs:
  download-convert-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget ffmpeg
          curl https://rclone.org/install.sh | sudo bash

      - name: Download m3u8 file
        run: |
          mkdir -p downloads
          wget -O downloads/playlist.m3u8 "https://api.vidio.com/videos/1776441/common_tokenized_playlist.m3u8?ott=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYWxsdXNlcnMiLCJ2aWRlb19pZCI6IjE3NzY0NDEiLCJjcmVhdGVkX2F0IjoxNzU5MTU3MzAwLCJleHRfZHVyYXRpb24iOjYwMH0.Fv3ebXXl0s_nU_WO9eAYgB0hiwZZh3ADZdeaokhEUuU"

      - name: Convert m3u8 to mp4
        run: |
          ffmpeg -i downloads/playlist.m3u8 -c copy downloads/output.mp4

      - name: Setup rclone config (decode base64)
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy downloads/output.mp4 gdrive:backup-folder --progress
