name: Download Video → GDrive + Telegram

on:
  workflow_dispatch:
    inputs:
      VIDEO_URL:
        description: "Masukkan URL video (m3u8 atau mp4)"
        required: true
        type: string
      OUTPUT_NAME:
        description: "Nama output file (tanpa .mp4)"
        required: true
        type: string

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl jq
          curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Download or Convert Video
        run: |
          mkdir -p downloads
          URL="${{ github.event.inputs.VIDEO_URL }}"
          NAME="${{ github.event.inputs.OUTPUT_NAME }}"

          if [[ "$URL" == *".m3u8"* ]]; then
            echo "▶ Detected HLS Stream - Converting to MP4..."
            ffmpeg -i "$URL" -c copy "downloads/${NAME}.mp4"
          else
            echo "▶ Detected MP4 - Downloading..."
            curl -L "$URL" -o "downloads/${NAME}.mp4"
          fi

      - name: Upload to Google Drive
        run: |
          NAME="${{ github.event.inputs.OUTPUT_NAME }}"
          echo "⬆ Uploading to Google Drive..."
          rclone copy "downloads/${NAME}.mp4" gdrive:backup-folder --progress

      - name: Upload to Telegram (Leech)
        run: |
          BOT="${{ secrets.BOT_TOKEN }}"
          CHAT="${{ secrets.CHAT_ID }}"
          NAME="${{ github.event.inputs.OUTPUT_NAME }}"

          echo "📤 Uploading to Telegram (sendDocument, streamed, up to 2GB)..."
          curl -X POST \
            -H "Expect:" \
            -F chat_id="$CHAT" \
            -F disable_content_type_detection="true" \
            -F document=@downloads/${NAME}.mp4";type=video/mp4" \
            "https://api.telegram.org/bot$BOT/sendDocument"

